### ISSUE TITLE
Nested AsciiPointer is not PInvoke compatible.

### ISSUE THREAD

**Issue by njust** [ralfbiedert/interoptopus#30]
Hi, first of all thanks for the great library! I am able to return a AsciiPointer from a method of my service, but when I try to return a AsciiPointer nested in a struct I get a runtime error: 

```csharp
System.Runtime.InteropServices.MarshalDirectiveException: Method's type signature is not PInvoke compatible.
   at My.Company.Interop.counter_service_nested_string(IntPtr context)
   at My.Company.CounterService.NestedString() in C:\Users\nico\tmp\lib_test\bindgen\generated\Interop.cs:line 288
   at ConsoleApplication42.Program.Main(String[] args) in C:\Users\nico\source\tmp\ConsoleApplication42\ConsoleApplication42\Program.cs:line 51
```

**Comment by ralfbiedert** [comment]
I think this is a C# issue and basically not fixable without giving up on `string` convenience as it hits the limits of C#'s interop magic.

IIRC if a struct contains `string` it becomes not blittable, meaning it can't participate in other structs that need to be blittable. C# handles one level of that, but not once it's nested. 

At this point the options basically are:

- Keep things as-is, translate `AsciiPointer` to `string` in structs but run into these issues. This means giving up on certain valid constructs (like nesting) but have nice `string` types in C#.
- Translate `AsciiPointer` to `IntPtr`. This allows for infinite nesting but makes accessing simple strings ugly. 
- It _might_ be possible to translate them to IntPtr and generate getter / setters, but I haven't looked into that, and I don't know whether that might cause other side effects.

**Comment by ralfbiedert** [comment]
I'm closing this with a `wontfix` for now as I don't see how this could be fixed without causing other issues. I'm happy to reopen this if C# changes or someone has a better idea.
